import React from "react";
import CityInternalLinks from "@/app/components/CityInternalLinks";
import FranchiseEnquiryForm from "@/app/components/FranchiseEnquiryForm";

const localBusinessSchema = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  name: "The Buyzaar Mart \u2013 Best Franchise Business in Gurgaon",
  description:
    "The Buyzaar Mart offers the best franchise business in Gurgaon with FOCM model, Hassle-Free Inventory Assurance, FSSAI licensing, and complete operational management.",
  url: "https://www.thebuyzaarmart.com/gurgaon/best-franchise-business-in-gurgaon",
  telephone: "+919217991727",
  email: "info@thebuyzaarmart.com",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Gurgaon",
    addressRegion: "Haryana",
    addressCountry: "IN",
  },
  areaServed: {
    "@type": "City",
    name: "Gurgaon",
  },
  openingHours: "Mo-Sa 09:00-19:00",
  priceRange: "\u20b9\u20b9",
  hasOfferCatalog: {
    "@type": "OfferCatalog",
    name: "Buyzaar Mart Franchise Formats in Gurgaon",
    itemListElement: [
      {
        "@type": "Offer",
        name: "Mini Mart Franchise",
        description:
          "Compact franchise format for society ground floors, colony-facing shops, and neighbourhood locations in Gurgaon",
      },
      {
        "@type": "Offer",
        name: "Super Mart Franchise",
        description:
          "Mid-sized organised daily needs store for township commercial areas and main market locations in Gurgaon",
      },
      {
        "@type": "Offer",
        name: "Hyper Mart Franchise",
        description:
          "Large-format flagship daily needs store for major commercial corridors in Gurgaon",
      },
    ],
  },
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "Why is daily needs retail the best franchise business in Gurgaon compared to food, fitness, or education franchises?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Daily needs is the only category in Gurgaon where spending is non-discretionary, non-seasonal, and generated by every single household every week. Food, fitness, and education franchises all depend on discretionary consumer decisions that fluctuate with season, budget, and sentiment. Daily needs retail does not \u2014 it runs on human behaviour that is constant and compounding.",
      },
    },
    {
      "@type": "Question",
      name: "What makes the FOCM model right for Gurgaon\u2019s investor profile?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Gurgaon\u2019s investors \u2014 corporate professionals, business owners, property holders \u2014 have capital but limited daily availability. The FOCM model means Buyzaar Mart manages all daily store operations while you own the franchise asset. You do not need to manage the retail floor.",
      },
    },
    {
      "@type": "Question",
      name: "What is the Hassle-Free Inventory Assurance and why does it matter?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "It is a contractual commitment in every Buyzaar Mart franchise agreement that expired and damaged goods are taken back by the company. In daily needs retail \u2014 where perishables and packaged food products carry expiry risk \u2014 this protection prevents the most common margin loss in retail from landing on the franchise investor.",
      },
    },
    {
      "@type": "Question",
      name: "Do I need retail or business management experience to own this franchise?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. The FOCM model is specifically designed for investors without operational retail experience. Buyzaar Mart manages all daily operations and trains your store team completely before opening.",
      },
    },
    {
      "@type": "Question",
      name: "What is the franchise agreement term?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "5 years with renewal criteria evaluated at the end of the term.",
      },
    },
    {
      "@type": "Question",
      name: "How long from enquiry to my franchise store opening in Gurgaon?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "8 to 12 weeks \u2014 covering location approval, franchise agreement, complete store setup, staff training, and grand opening marketing.",
      },
    },
    {
      "@type": "Question",
      name: "How do I find out which franchise format and location is right for my Gurgaon investment?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Call 9217991727 or fill in the enquiry form on this page. Our Gurgaon franchise advisor conducts a full location evaluation and provides a personalised format recommendation and investment breakdown for your specific site \u2014 before any commitment is made.",
      },
    },
  ],
};

const Content = () => {
  return (
    <div className="min-h-screen bg-white pt-0">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(localBusinessSchema),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(faqSchema),
        }}
      />

      <div className="flex flex-col lg:flex-row">
        <div className="order-1 flex-1 px-4 py-0 sm:px-8 md:px-16 lg:order-1">
          <div className="max-w-4xl space-y-4 font-serif font-medium leading-relaxed text-gray-700">
            <h1 className="mt-8 text-2xl font-medium text-gray-900 sm:text-3xl">
              Best Franchise Business in Gurgaon &#8211; What the Right
              Investment Actually Looks Like
            </h1>

            <p>
              Gurgaon has no shortage of franchise options. What it has a
              shortage of is franchise businesses that match the city&#39;s
              unique investor profile &#8212; high capital, limited daily
              availability, and a genuine expectation of professional management
              behind the investment.
            </p>

            <p>
              Walk into any franchise expo in Delhi NCR and you will find
              hundreds of brands competing for attention with bold numbers and
              aspirational pitch decks. Some are legitimate. Many are not. And
              almost none of them are designed around the specific reality of a
              Gurgaon investor &#8212; a city where the people with the capital
              to invest in a serious franchise business are also the people with
              the least time to run one daily.
            </p>

            <p>
              This page gives you an honest, structured answer to the question
              every Gurgaon investor is actually asking when they search for the
              best franchise business here: which investment generates reliable
              daily income from a business that runs professionally without
              requiring my constant presence?
            </p>

            <p>
              The answer is not a brand. It is a category, a model, and then a
              brand &#8212; in that order.
            </p>

            <h2 className="text-xl font-medium text-gray-900 sm:text-2xl">
              Part 1 &#8212; The Category That Makes the Best Franchise Business
              in Gurgaon
            </h2>

            <p>
              Every franchise business in Gurgaon &#8212; regardless of brand
              &#8212; lives or dies by the strength of its underlying demand.
              And demand strength in any category is measured by one question:
              how often does a typical Gurgaon household spend in this category,
              and does that spending depend on discretionary decisions?
            </p>

            <p>
              Run this test across the most commonly pitched franchise
              categories in Gurgaon:
            </p>

            <h3 className="font-medium text-gray-900">
              Food and Beverage Franchises
            </h3>

            <p>
              Gurgaon has a large, affluent market for dining and food service.
              But restaurant and QSR franchises are discretionary by nature
              &#8212; customers choose when to eat out, influenced by mood,
              budget, social plans, and the season. Monday lunch is not the same
              as Saturday evening. January is not the same as December. A food
              franchise in Gurgaon can perform brilliantly on weekends and
              struggle mid-week. It can peak in winter and slow in summer. The
              demand exists &#8212; but it fluctuates, and that fluctuation
              creates income variability that makes financial planning complex.
            </p>

            <h3 className="font-medium text-gray-900">
              Fitness and Wellness Franchises
            </h3>

            <p>
              Gurgaon&#39;s health-conscious professional population creates
              strong demand for gyms, yoga studios, and wellness centres.
              However, this category has two structural challenges: high
              operational complexity requiring skilled staff who are difficult to
              retain, and income that depends on membership renewals which are
              genuinely discretionary. Members cancel during travel-heavy
              periods, tight financial quarters, and busy professional seasons.
              The franchise depends on continuous active marketing and retention
              effort that demands heavy owner involvement.
            </p>

            <h3 className="font-medium text-gray-900">
              Education and Coaching Franchises
            </h3>

            <p>
              Real demand in Gurgaon&#39;s residential family market &#8212; but
              structurally seasonal. Revenue peaks around admission cycles and
              drops sharply in summer. Fee collection requires ongoing parent
              engagement. Teacher quality and retention directly determine
              franchise performance in ways that are difficult to control from
              an ownership distance.
            </p>

            <h3 className="font-medium text-gray-900">
              Beauty and Salon Franchises
            </h3>

            <p>
              Discretionary spend category with intense local competition in
              Gurgaon from unorganised salons offering deeply discounted
              pricing. Building a loyal client base takes 12 to 18 months of
              consistent service quality delivery. Margin pressure from local
              competition is persistent.
            </p>

            <h3 className="font-medium text-gray-900">
              Daily Needs Retail Franchise
            </h3>

            <p>
              Every household in Gurgaon &#8212; in every sector, at every
              income level, in every season &#8212; purchases groceries, FMCG
              products, dairy, personal care, and household essentials every
              week. This spending is not discretionary. It does not fluctuate
              with mood, season, economy, or social plans. It is as consistent
              as the human requirement to eat, clean, and maintain a household.
            </p>

            <p>
              A daily needs retail franchise in Gurgaon serves this spending
              &#8212; the most consistent, most predictable, most
              recession-proof consumer behaviour in the city&#39;s entire retail
              market.
            </p>

            <p>
              This is why daily needs retail is the category behind the best
              franchise business in Gurgaon for investors who want consistent,
              reliable income rather than boom-and-bust retail cycles.
            </p>

            <h2 className="text-xl font-medium text-gray-900 sm:text-2xl">
              The Model That Makes It Work for Gurgaon&#39;s Investor Profile
            </h2>

            <p>
              Identifying the right category is half the answer. The other half
              is the model &#8212; the operational structure that determines
              whether you can actually own this franchise business alongside
              your existing professional or business commitments.
            </p>

            <p>
              Most daily needs retail franchises in India operate on a
              self-operated model. You invest in the brand, you receive systems
              and support, and you manage the store yourself &#8212; daily
              inventory, staff management, supplier coordination, marketing, and
              compliance. This model works for investors who are willing and
              available to operate a retail floor full-time.
            </p>

            <p>
              Gurgaon&#39;s investor base is not predominantly composed of
              these investors. It is composed of:
            </p>

            <ul className="ml-4 list-inside list-disc space-y-2">
              <li>
                Corporate professionals at MNCs and IT companies who leave
                early, return late, and have zero bandwidth for daily retail
                floor management
              </li>
              <li>
                Business owners who already run one business and want a second
                income stream, not a second full-time job
              </li>
              <li>
                Property owners with a commercial unit in a residential society
                who want it generating organised retail income without
                personally operating a store
              </li>
              <li>
                High-net-worth individuals who understand the daily needs retail
                opportunity but require professional management behind their
                investment
              </li>
            </ul>

            <p>
              For all of these investor profiles, the self-operated franchise
              model creates an immediate structural problem: the franchise
              requires more daily involvement than the investor can provide.
              This is the most common reason good franchise investments in
              Gurgaon underperform &#8212; not because the category is wrong,
              but because the model does not fit the investor.
            </p>

            <p>
              The Buyzaar Mart FOCM model &#8212; Franchise Owned, Company
              Managed &#8212; resolves this completely.
            </p>

            <p>
              You own the franchise. You invest in it, hold the franchise rights
              under a 5-year formal agreement, and build a business asset in one
              of India&#39;s most valuable consumer markets.
            </p>

            <p>
              Buyzaar Mart manages the franchise. Every operational element of
              your daily needs store &#8212; setup, branding, POS technology,
              inventory management, supply chain, staff training, daily
              operations under tested SOP, marketing, and performance monitoring
              &#8212; is handled by our operations team.
            </p>

            <p>
              This is the model that makes daily needs retail the best franchise
              business in Gurgaon for investors who want to own a professionally
              run retail asset without running it themselves.
            </p>

            <h2 className="text-xl font-medium text-gray-900 sm:text-2xl">
              The Brand That Delivers Both
            </h2>

            <p>
              Category and model identify what the best franchise business in
              Gurgaon looks like structurally. The brand determines whether that
              structure is delivered with the depth, consistency, and legal
              credibility it requires.
            </p>

            <p>
              Here is what The Buyzaar Mart brings to your franchise business in
              Gurgaon:
            </p>

            <h3 className="font-medium text-gray-900">
              Complete Operational Management Under FOCM
            </h3>

            <ul className="ml-4 list-inside list-disc space-y-2">
              <li>
                Store design and setup, interior layout, shelving, fixtures,
                branding, POS technology &#8212; all handled by our team before
                your store opens.
              </li>
              <li>
                Daily operations under a tested Standard Operating Process
                covering inventory control, restocking discipline, customer
                service standards, hygiene routines, and staff management.
              </li>
              <li>
                Supply chain access through our FMCG distributor network and
                vendor relationships &#8212; competitive product pricing that
                independent retailers in Gurgaon cannot access.
              </li>
              <li>Staff training before opening day.</li>
              <li>
                Grand opening marketing and ongoing hyperlocal digital campaigns
                targeting your specific Gurgaon catchment.
              </li>
              <li>
                Real-time KPI dashboards and scheduled operational audits.
              </li>
            </ul>

            <p>
              This is the operational depth that &#8220;company managed&#8221;
              in FOCM actually means at Buyzaar Mart. Not guidance. Not a
              manual. Active, structured management of your franchise business
              by our operations team.
            </p>

            <h3 className="font-medium text-gray-900">
              Hassle-Free Inventory Assurance &#8212; The Protection That
              Defines the Best Franchise
            </h3>

            <p>
              In retail, inventory that expires before selling is the most
              persistent and most underestimated financial risk. For independent
              retailers in Gurgaon, this cost is absorbed entirely out of their
              own margins. For Buyzaar Mart franchise investors, it is not.
            </p>

            <p>
              Expired and damaged goods are taken back by Buyzaar Mart. This is
              a contractual commitment in every franchise agreement &#8212;
              written, enforceable, and unconditional. It means your franchise
              business investment in Gurgaon is protected from the silent margin
              erosion that quietly destroys independent retail stores and
              self-operated franchise outlets across the city.
            </p>

            <p>
              No other daily needs franchise in Gurgaon offers this protection
              as a contractual standard. It is one of the most concrete reasons
              the Buyzaar Mart franchise is the best franchise business in
              Gurgaon for serious investors.
            </p>

            <h3 className="font-medium text-gray-900">
              Three Formats &#8212; One Right for Your Gurgaon Location
            </h3>

            <ul className="ml-4 list-inside list-disc space-y-2">
              <li>
                <strong>Mini Mart</strong> &#8212; The compact daily needs
                franchise for residential society ground floors, colony-facing
                shops, and neighbourhood-level commercial units. High-repeat
                daily footfall from a captive residential catchment. The most
                accessible entry point for first-time franchise investors in
                Gurgaon.
                <br />
                <em>Best locations:</em> Housing society retail units across
                Dwarka Expressway sectors, DLF Phase society markets, Palam
                Vihar colony lanes, Sushant Lok inner residential roads, South
                City residential blocks, Sector 56&#8211;58 colony shops.
              </li>
              <li>
                <strong>Super Mart</strong> &#8212; A comprehensive mid-sized
                daily needs franchise for colony chowks, township commercial
                blocks, and main residential sector road locations. Wider
                catchment, larger average basket size, stronger weekly revenue.
                <br />
                <em>Best locations:</em> Dwarka Expressway township commercial
                blocks, Southern Peripheral Road commercial units, Golf Course
                Extension areas, Palam Vihar main market, Sector 45&#8211;46
                commercial spaces.
              </li>
              <li>
                <strong>Hyper Mart</strong> &#8212; A large-format flagship
                daily needs franchise for high-footfall main road commercial
                zones. The anchor organised store for its entire Gurgaon zone.
                <br />
                <em>Best locations:</em> NH-48 frontages, Sohna Road commercial
                corridor, Golf Course Road main markets, Sector 14 and Sector
                45 main markets, Manesar commercial zones.
              </li>
            </ul>

            <p>
              Our team evaluates your proposed Gurgaon site and recommends the
              right format with a personalised investment breakdown before any
              commitment is made.
            </p>

            <h3 className="font-medium text-gray-900">
              Government-Verified Certifications &#8212; The Trust Foundation
            </h3>

            <p>
              In Gurgaon&#39;s quality-conscious consumer market, the
              certifications behind your franchise business determine how
              quickly your store earns community trust and daily loyalty.
            </p>

            <ul className="ml-4 list-inside list-disc space-y-2">
              <li>
                <strong>FSSAI Licensed</strong> &#8212; Food Safety and
                Standards Authority of India certified. Every food product,
                dairy item, and packaged good in your store meets national food
                safety standards. In a city where consumers read labels and make
                deliberate quality decisions, FSSAI certification at your
                entrance converts first-time visitors into regular shoppers.
              </li>
              <li>
                <strong>GST Registered</strong> &#8212; Full Goods and Services
                Tax compliance. Proper billing and formal tax registration
                &#8212; the baseline expectation from any retail store that
                Gurgaon&#39;s professional population regularly shops at.
              </li>
              <li>
                <strong>MSME Certified</strong> &#8212; Recognised by the
                Ministry of MSME, Government of India. Institutional credibility
                that positions your Buyzaar Mart franchise above every
                unregistered competitor in your Gurgaon locality from day one.
              </li>
            </ul>

            <h2 className="text-xl font-medium text-gray-900 sm:text-2xl">
              Why Gurgaon&#39;s Fastest-Growing Areas Make This the Best Time
              to Invest
            </h2>

            <p>
              The best franchise business in Gurgaon is not only about category
              and model &#8212; it is also about timing. And right now, three
              forces are converging in Gurgaon that make the daily needs retail
              franchise opportunity genuinely time-sensitive.
            </p>

            <p>
              Possession handovers are at their highest volume in years. Dwarka
              Expressway and Southern Peripheral Road deliveries are peaking
              &#8212; tens of thousands of new families are establishing their
              daily shopping habits right now in new residential corridors where
              organised retail is almost entirely absent. The franchise investor
              who opens in the right location here today captures this
              community&#39;s loyalty before any competition arrives. The one
              who waits finds those habits already established &#8212; at
              someone else&#39;s store.
            </p>

            <p>
              Organised daily needs retail at the neighbourhood level remains
              thin. Gurgaon&#39;s large organised retail chains operate on main
              roads and in malls. Society-level and colony-level daily needs
              retail &#8212; where the highest-frequency repeat purchases happen
              &#8212; is still largely served by unorganised kirana stores in
              most of the city&#39;s residential interior. This gap is the
              franchise opportunity. It will close as the market matures
              &#8212; but it has not closed yet.
            </p>

            <p>
              The FOCM model makes entry more accessible than a self-operated
              franchise ever could. For Gurgaon&#39;s investor profile
              &#8212; professional, busy, capital-ready &#8212; the FOCM model
              removes the single biggest barrier to franchise ownership in this
              city. You do not need to leave your job to own the best franchise
              business in Gurgaon. You need the right partner, the right
              location, and the commitment to invest in a professionally managed
              business that earns from Gurgaon&#39;s most reliable consumer
              demand.
            </p>

            <h2 className="text-xl font-medium text-gray-900 sm:text-2xl">
              Frequently Asked Questions &#8212; Best Franchise Business in
              Gurgaon
            </h2>

            <div className="mt-4 space-y-4">
              <div>
                <h3 className="font-medium text-gray-900">
                  1. Why is daily needs retail the best franchise business in
                  Gurgaon compared to food, fitness, or education franchises?
                </h3>
                <p className="mt-2">
                  Daily needs is the only category in Gurgaon where spending is
                  non-discretionary, non-seasonal, and generated by every single
                  household every week. Food, fitness, and education franchises
                  all depend on discretionary consumer decisions that fluctuate
                  with season, budget, and sentiment. Daily needs retail does
                  not &#8212; it runs on human behaviour that is constant and
                  compounding.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-900">
                  2. What makes the FOCM model right for Gurgaon&#39;s investor
                  profile?
                </h3>
                <p className="mt-2">
                  Gurgaon&#39;s investors &#8212; corporate professionals,
                  business owners, property holders &#8212; have capital but
                  limited daily availability. The FOCM model means Buyzaar Mart
                  manages all daily store operations while you own the franchise
                  asset. You do not need to manage the retail floor. This makes
                  the best franchise business in Gurgaon genuinely accessible to
                  investors who could not realistically operate a self-managed
                  franchise alongside their existing commitments.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-900">
                  3. What is the Hassle-Free Inventory Assurance and why does it
                  matter?
                </h3>
                <p className="mt-2">
                  It is a contractual commitment in every Buyzaar Mart franchise
                  agreement that expired and damaged goods are taken back by the
                  company. In daily needs retail &#8212; where perishables and
                  packaged food products carry expiry risk &#8212; this
                  protection prevents the most common and most persistent margin
                  loss in retail from landing on the franchise investor. No
                  other daily needs franchise brand in Gurgaon offers this as a
                  contractual standard.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-900">
                  4. How do I find out which franchise format and location is
                  right for my Gurgaon investment?
                </h3>
                <p className="mt-2">
                  Call 9217991727 or fill in the enquiry form on this page. Our
                  Gurgaon franchise advisor conducts a full location evaluation
                  and provides a personalised format recommendation and
                  investment breakdown for your specific site &#8212; before any
                  commitment is made.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-900">
                  5. Do I need retail or business management experience to own
                  this franchise?
                </h3>
                <p className="mt-2">
                  No. The FOCM model is specifically designed for investors
                  without operational retail experience. Buyzaar Mart manages
                  all daily operations and trains your store team completely
                  before opening.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-900">
                  6. What is the franchise agreement term?
                </h3>
                <p className="mt-2">
                  5 years with renewal criteria evaluated at the end of the
                  term.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-gray-900">
                  7. How long from enquiry to my franchise store opening in
                  Gurgaon?
                </h3>
                <p className="mt-2">
                  8 to 12 weeks &#8212; covering location approval, franchise
                  agreement, complete store setup, staff training, and grand
                  opening marketing.
                </p>
              </div>
            </div>

            <div className="mt-12 rounded-r-lg border-l-4 border-green-500 bg-green-50 p-8">
              <h2 className="mb-4 text-xl font-medium text-gray-900 sm:text-2xl">
                The Best Franchise Business in Gurgaon Is a Decision, Not a
                Discovery
              </h2>

              <p className="mb-4 text-gray-800">
                You have already done the research. You already know
                Gurgaon&#39;s franchise market needs the right combination of
                category, model, and brand. The Buyzaar Mart daily needs
                franchise delivers all three &#8212; in a format that fits
                Gurgaon&#39;s investor profile, in a city whose residential
                expansion is creating new franchise opportunities every month.
              </p>

              <p className="mb-4 text-gray-800">
                The families in Dwarka Expressway sectors, DLF Phase colonies,
                Palam Vihar pockets, and Sushant Lok residential lanes are
                spending on daily essentials this week. And next week. And every
                week after that.
              </p>

              <p className="mb-4 font-semibold text-gray-800">
                Your franchise business earns from every single one of those
                weeks &#8212; from the first day it opens.
              </p>

              <p className="text-gray-800">
                <span className="font-semibold">Call / WhatsApp:</span>{" "}
                9217991727
              </p>

              <p className="text-gray-800">
                <span className="font-semibold">Email:</span>{" "}
                info@thebuyzaarmart.com
              </p>

              <p className="text-gray-800">
                <span className="font-semibold">Business Hours:</span> Monday
                &#8211; Saturday, 9:00 AM &#8211; 7:00 PM
              </p>

              <p className="mt-4 text-gray-800">
                <span className="font-semibold">Apply instantly:</span>{" "}
                <a
                  href="https://www.thebuyzaarmart.com/gurgaon/best-franchise-business-in-gurgaon"
                  className="font-semibold text-green-600 hover:underline"
                >
                  thebuyzaarmart.com/gurgaon/best-franchise-business-in-gurgaon
                </a>
              </p>
            </div>
          </div>

          <CityInternalLinks
            city="gurgaon"
            currentSlug="/gurgaon/best-franchise-business-in-gurgaon"
          />
        </div>

        <div className="order-2 w-full p-8 lg:order-2 lg:w-[500px]">
          <div className="lg:sticky lg:top-28">
            <FranchiseEnquiryForm />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Content;